### ISSUE TITLE
How to align text to left right and center

### ISSUE THREAD

**Issue by rohanisme** [AhmedElsayed94/SunmiPrinterSdk#5]

**Comment by AhmedElsayed94** [comment]
you can use print layout feature and make it in xml first then print the
whole layout
or you can calculate it manually the width of the paper as far as i
remember about 364 dp

**Comment by rohanisme** [comment]
The font after printing looks compressed any idea how i can fix it

**Comment by eriknyk** [comment]
@AhmedElsayed94 How or where I can find documentation or examples of using "print layout feature"? Regards
